### PR TITLE
Fix download link

### PR DESCRIPTION
**Pull request by timkelty**
The filename link should just be a shortcut to download the csv, right?
If so, this should do it.

### CODE REVIEW

**Comment by davist11** [comment]
I believe it was supposed to be a link to view the history of that import attempt.

**Comment by timkelty** [comment]
Ah ok...presumably what `craft/plugins/import/templates/history/_log.twig` is for....

**Comment by boboldehampsink** [comment]
It should be `{{ url('import/history', { id: item.id }) }}`

**Comment by timkelty** [comment]
Right...I'm not seeing where you're including `_log.twig` at all though. That link doesn't do anything for me. Am I missing something?

**Comment by timkelty** [comment]
Sorry I see it now...in your routes

**Comment by timkelty** [comment]
So I think we either need to change it to `url('import/history/'~item.id)` or change the route.

**Comment by timkelty** [comment]
Ok - latest PR has the history view working again.

**Pull request merged**
